baseURL: "/"
languageCode: "en-us"
title: "Kura Bloodlust"
paginate: 10
# disqusShortname
theme: mainroad

author:
    name: "Kura Bloodlust"
    bio: "Kura, also known as Criss, is an enthusiastic developer, specialized in Go and NodeJS applications"
    avatar: "img/avatar.png"

menu:
    main:
        - name: "Blog"
          weight: -666
          identifier: "posts"
          url: "/"

params:
    subtitle: "Random thoughts and trashy animes"
    description: "Kura's blog about anything and everything"
    opengraph: true
    readmore: false
    leftsidebar: false
    post_navigation: true
    postSections:
        - posts
    dateformat: 2006-01-2
    authorbox: true

    widgets:
        search: true
        recent_articles: true
        recent_articles_num: 5
        categories: true
        tags: true
        tags_counter: true

        social_twitter: IAmKura
        social_keybase: kurabloodlust
        social_mastodon: niu.moe/@kura
        social_github: cking
        social_email: contact@kurabloodlust.eu
